webhook1:
  name: "webhook 1"
  url: "https://weather-alerts.com/api"
  zip_code: 10000

webhook2:
  name: "webhook 2"
  url: "https://weather-alerts.com/api"
  zip_code: 20000

webhook3:
  name: "webhook 3"
  url: "https://weather-alerts.com/api"
  zip_code: 30000

